### PR TITLE
Fix read enables for smems

### LINKED ISSUE #286: Unconditional SeqMem reads turn into never executed reads
Currently, if there is no 'when' infront of the address heading into a SeqMem read address, firrtl creates a constant '0' for the read enable. It should be a constant '1'!

eg:
    val mem = SeqMem(1 << addrBits.size, Vec(beatBytes, Bits(width = 8)))
    val bar = mem.read(counter) // read address never follows counter!

### PR DESCRIPTION
**Pull request by donggyukim**
* CHANGE BASE TO MASTER BEFORE MERGE
* Fixes #286

@terpstra Can you confirm this works well with your examples?

### CODE REVIEW

File: src/test/scala/firrtlTests/ChirrtlMemSpec.scala [hunk 1]
```diff
@@ -0,0 +1,136 @@
...
+    node T_0 = add(io.counter, UInt<1>("h01"))
+    node temp = tail(T_0, 1)
+    read mport bar = mem[temp], clk
+    when io.wen :
+      write mport T_1 = mem[io.counter], clk
+      T_1 <= io.in
+    io.out <= bar
+""".stripMargin
+
+    val annotaitonMap = AnnotationMap(Nil)
```
Comment (azidar) [inline src/test/scala/firrtlTests/ChirrtlMemSpec.scala]: annotation

File: src/test/scala/firrtlTests/ChirrtlMemSpec.scala [hunk 2]
```diff
@@ -0,0 +1,136 @@
...
+  }
+
+  object MemEnableCheck extends Transform with SimpleRun {
+    def execute(c: Circuit, map: AnnotationMap) =
+      run(c, Seq(ConstProp, MemEnableCheckPass))
+  }
+
+  def transform = MemEnableCheck
+
+  "Seqential Memory" should "have correct enable signals" in {
```
Comment (azidar) [inline src/test/scala/firrtlTests/ChirrtlMemSpec.scala]: Sequential

File: src/test/scala/firrtlTests/ChirrtlMemSpec.scala [hunk 3]
```diff
@@ -0,0 +1,136 @@
...
+    read mport bar = mem[counter], clk
+    when io.ren:
+      counter <= add(counter, UInt<1>("h1"))
+    when io.wen :
+      write mport T_1 = mem[io.counter], clk
+      T_1 <= io.in
+    io.out <= bar
+""".stripMargin
+
+    val annotaitonMap = AnnotationMap(Nil)
```
Comment (azidar) [inline src/test/scala/firrtlTests/ChirrtlMemSpec.scala]: annotation

**Comment by azidar** [comment]
Add comments explaining the Check Pass and what conditions specifically it checks, and fix typos. After that, lgtm.
